class Actividades {
  Map<String, double> actividadesEconomicas = {
    "Industria de la carne": 1.00,
    "Industria lacteas": 1.00,
    "Industria de conservacion de frutas, hortalizas y similares": 1.00,
    "Fabricación de aceites y grasas animales y/o vegetales": 1.00,
    "Industrias de productos alimenticios diversos para el consumo humano":
        1.70,
    "Procesadora de Cacao, Chocolate, Bombones y sus derivados": 1.70,
    "Industrias de alimentos y demás productos para el consumo animal.": 1.70,
    "Fabricación de bebidas no alcohólicas": 2.50,
    "Fabricación de bebidas alcohólicas obtenidas por destilación de especies vegetales nacionales)":
        3.00,
    "Fabricación de las demás bebidas alcohólicas y licores": 4.00,
    "Manufactura de tabaco, cigarrillos y derivados": 5.00,
    "Industrias textil": 1.50,
    "Fabricación de prendas de vestir y demás accesorios de vestir": 1.50,
    "Industria del cuero natural, sintéticos y conexas.": 1.50,
    "Fabricación de calzado, artículos de talabartería y guarnicionería": 1.50,
    "Industrias de la madera y corcho": 1.50,
    "Fabricación de papel y cartón y productos de estas materias": 1.50,
    "Industria de impresión, reproducción, editorial y artes gráficas": 1.00,
    "Fabricación de envases, empaques, embalajes": 1.00,
    "Fabricación de productos a partir de los derivados del petróleo del caucho y plástico.":
        1.50,
    "Industrias químicas": 1.50,
    "Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico.":
        1.00,
    "Fabricación de productos de higiene, cosméticos y otros": 1.50,
    "Industria de la transformación de otros productos minerales no metálicos e insumos para la construcción":
        3.00,
    "Industria metalúrgica y metalmecánica": 1.00,
    "Fabricación de productos elaborados de metal, excepto maquinarias y equipos.":
        1.50,
    "Fabricación de equipos, materiales e instrumentos de informática, electrónicos y eléctricos.":
        1.50,
    "Fabricación de maquinarias y otros equipos e instrumentos.": 1.50,
    "Fabricación de mobiliario": 2.00,
    "Fabricación de utensilios de uso industrial y domestico": 2.00,
    "Fabricación y ensamblaje de vehículos de motor, remolque o semirremolque":
        3.00,
    "Fabricación de otros equipos de transporte": 2.00,
    "Fabricación de autopartes y repuestos para vehículos terrestres": 2.00,
    "Otras industrias manufactureras": 2.00,
    "Construcción de viviendas y edificios": 2.00,
    "Obras de ingeniería civil": 2.00,
    "Actividades especializadas de construcción": 3.00,
    "Construcción y servicios a la industria petrolera, petroquímica y similares":
        3.00,
    "Mayor de materias primas y similares": 1.50,
    "Mayor de alimentos": 1.70,
    "Mayor de bebidas no alcohólicas": 3.00,
    "Mayor de bebidas alcohólicas": 5.00,
    "Mayor de cigarrillos, tabacos y derivados": 6.00,
    "Mayor de productos textiles, del cuero, sintéticos, del calzados, deportivos, prendas, accesorios de vestir y conexos":
        1.50,
    "Mayor de productos y derivados de madera, corcho y artes gráficas": 1.50,
    "Mayor de productos químicos, derivados del petróleo y afines": 1.50,
    "Mayor de cauchos": 1.50,
    "Mayor de productos plásticos y similares": 1.50,
    "Mayor de medicamentos, productos de uso farmacéuticos y similares": 1.00,
    "Mayor de productos de higiene, cosméticos y otros": 1.50,
    "Mayor de materiales y productos para la construcción, metálicos, no metálicos y otro":
        1.50,
    "Mayor de productos, maquinaria y equipos diversos, así como sus repuestos y accesorios":
        1.50,
    "Otras actividades de comercio al mayor": 2.00,
    "Detal de materias primas y similares": 1.50,
    "Detal de alimentos": 1.70,
    "Panadería": 1.70,
    "Frutería": 1.70,
    "Carnicería o Frigoríficos": 1.70,
    "Pescadería": 1.70,
    "Charcutería": 1.70,
    "Bodegas u otros establecimientos": 1.70,
    "Detal de bebidas no alcohólicas": 3.00,
    "Detal de bebidas alcohólicas": 5.00,
    "Detal de cigarrillos, tabacos y derivados": 6.00,
    "Detal de productos textiles, del cuero, sintéticos, del calzados, deportivos, prendas, accesorios de vestir y conexos":
        2.00,
    "Detal de productos y derivados de madera, corcho y artes gráficas": 2.00,
    "Detal de productos químicos, derivados del petróleo y afines": 2.50,
    "Detal de cauchos": 2.00,
    "Detal de productos plásticos y similares": 2.00,
    "Detal de medicamentos, productos de uso farmacéuticos y similares": 1.00,
    "Detal de productos de higiene, cosméticos y otros": 1.70,
    "Detal de materiales y productos para la construcción, metálicos, no metálicos y otros":
        2.00,
    "Ferreterías": 2.00,
    "Detal de productos, maquinarias y equipos diversos, así como sus repuestos y accesorio":
        2.00,
    "Detal de vehículos": 3.00,
    "Detal repuestos y accesorios": 2.00,
    "Caucheras y Talleres Mecánicos": 2.00,
    "Detal de muebles; artefactos y artículos para la industria, comercio y domésticos":
        2.00,
    "Detal de equipos e instrumentos diversos, eléctricos, electrónicos, de energía solar, así como sus repuestos, accesorios y consumibles":
        3.00,
    "Detal de productos y artefactos diversos en general": 3.00,
    "Floristería": 3.00,
    "Librería": 3.00,
    "Detal de productos y artículos y materiales diversos para animales.": 2.00,
    "Detal de alimento para animales": 1.70,
    "Venta de joyas, relojes y piedras preciosas": 6.00,
    "Supermercados, hipermercados, automercados...": 2.50,
    "Tiendas por departamento": 2.50,
    "Otras actividades de comercio al detal no especificadas en los sub-ramos anteriores":
        3.00,
    "Servicio de alimentos y bebidas preparados": 4.00,
    "Restaurantes sin venta de Licor": 4.00,
    "Heladería, alimentos y bebidas preparados": 3.00,
    "Restaurantes con venta de Licor": 5.00,
    "Fuentes de Soda sin Venta de Licor": 4.00,
    "Fuentes de Soda con Venta de Licor": 5.00,
    "Servicio deportivo, de recreación y eventos": 3.00,
    "Agencias de Festejos": 2.50,
    "Juegos y Apuestas lícitas": 3.00,
    "Hoteles y posadas": 2.00,
    "Pensiones y Afines": 1.50,
    "Transporte de pasajeros": 1.50,
    "Transporte de carga terrestre": 2.00,
    "Servicios de almacenaje": 2.00,
    "Estaciones surtidora de combustibles": 0.25,
    "Servicios de salud": 1.50,
    "Servicios de estética, belleza y cuidados personales": 2.00,
    "Servicios de atención, cuidado y estética para animales": 3.00,
    "Limpieza, mantenimiento, ornato y fumigación": 1.70,
    "Servicios de formación, vigilancia y servicios diversos prestados por agencias especializadas":
        3.00,
    "Servicios Funerarios": 3.00,
    "Servicio de estacionamiento": 2.00,
    "Arrendamientos diversos de maquinarias y equipos en general": 2.00,
    "Servicios radiodifusión y telecomunicaciones": 1.00,
    "Servicios de tecnología y medios de difusión": 3.00,
    "Servicios fotográficos, de imprenta y reproducción": 3.00,
    "Servicios de instalación y reparación de artefactos, equipos y accesorios":
        3.00,
    "Servicios de mecánica, electricidad, gas y similares.": 3.00,
    "Bancos universales e instituciones financieras": 3.00,
    "Instituciones de seguros y similares.": 3.00,
    "Servicios inmobiliarios, de administración de inmuebles y actividades de índole similar":
        3.00,
    "Servicio de publicidad": 3.00,
    "Servicio de mantenimiento y reparación a la industria petrolera.": 2.50,
    "Servicio de mantenimiento y reparación a la industria gasífera y petroquímica.":
        3.00,
    "Servicio de mantenimiento preventivo y correctivo, remodelaciones menores y adecuaciones de obras civiles":
        3.00,
    "Servicios de asesorias profesionales y técnicas": 3.00,
    "Actividades industriales, comerciales, de servicios y de índole similar no especificadas en el clasificador de actividades económicas":
        3.00,
  };
}
